# Copyright (c) 2025 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# SPDX-License-Identifier: MIT

from typing import List, Optional

from autogen_core.models import UserMessage, SystemMessage

from ..utils.llm_factory import get_model_client


async def able_table(
    hypothesis: str,
    research_document: str,
    local_data_document: str,
    local_context: str,
    # Duck-typed message list, matching researcher/refiner: callers pass
    # agentchat TextMessages, which the model client maps permissively.
    previous_run: Optional[list] = None,
) -> str:
    """
    Generate a PEAK ABLE table based on the given hypothesis and research document.

    Args:
        hypothesis (str): The threat hunting hypothesis.
        research_document (str): The research document containging info about the
            behavior or technique being hunted for.
        local_data_document (str): The local data document containing info about the
            data sources available to the user.
        local_context (str): Additional local context about the user's environment.

    Returns:
        str: The output generated by the LLM.
    """
    # Define the system prompt for the hypothesizer
    system_prompt = """
        You are an expert in cybersecurity threat hunting, especially the PEAK
        Threat Hunting Framework. 

        Even when you have a clear and testable hypothesis, you still need to know a few
        things before you can start hunting. You need to know possible indicators of the
        activity, data source(s) you need to examine, and which parts of the network the
        activity is happening in. 

        PEAK incorporates the ABLE method to help you capture the critical pieces of
        your hunting hypothesis, which include:

            - Actor: The threat actor (or sometimes the general type of threat actor) that you are
                looking for. Many behaviors are not tied to a specific actor, so you won’t always
                need to specify this part. But if you do, it can supply valuable context to help
                with the rest of your hunt.
            - Behavior: The specific activity you’re trying to find — sometimes called TTPs (Tactics,
                Techniques, and Procedures). Instead of hunting for an entire attack lifecycle’s
                worth of behavior, focus on one or two pieces at a time.
            - Location: The part(s) of your organization’s network where you would expect to find the
                behavior (e.g., “end-user desktops,” “internet-facing web servers,” or even just
                “internal” versus “perimeter”). A proper location helps narrow the scope of your
                hunt, making it easier and more efficient.
            - Evidence: A combination of which data source(s) you’d need to consult to find the activity
                and what it would look like if it were present. You’ll need to know these when you
                plan your data collection and create your analysis strategy.

        Example: Using ABLE to hunt DNS exfiltration

        Consider the following hypothesis: “PIFFLING PANGOLIN may be exfiltrating
        sensitive financial data using DNS tunneling.” Here’s how you might break this
        down using the ABLE framework.
    
        Actor: Although financial data would appeal to many cybercriminals, this
        hypothesis is about a specific group. Understanding this actor’s typical
        operations may give you clues to aid in your hunt, such as known C2 domains
        or specific tools they use for DNS tunnels.
    
        Behavior: The behavior you’re hunting for is data exfiltration through DNS
        tunneling. By focusing on this specific tactic, you can narrow down your
        investigation and concentrate on relevant indicators of compromise.
    
        Location: The hypothesis suggests that the finance department is being
        targeted. This pinpoints the parts of the network that you need to scrutinize —
        the finance network for the source of the data and the network perimeter for
        the internet-based exfiltration.
    
        Evidence: To detect DNS tunneling, examine DNS query logs or full passive
        DNS logs. Look for unusually large or frequent DNS queries, odd DNS query
        types or indicators of known DNS tunneling tools.
    
        
        As the ABLE agent, your task is to read the user's hunting hypothesis as
        well as the research document and generate a PEAK ABLE table. Take your time 
        and think carefully about the hypothesis and the research document in order
        to produce the best possible table. 

        The output should be a Markdown document with the following format:
            - Title: 1st level header with the title "PEAK ABLE Table: " followed by the 
                common name for the technique being hunted for. This should be the first line
                of your output.
            - Hypothesis: Italic text with the text "Hypothesis: " followed by the user's
                hunting hypothesis.
            - ABLE Table: An easy-to-read table with the following columns:
                - "ABLE Element": The name of the ABLE element (Actor, Behavior, Location, Evidence)
                - An untitled column with the content of the ABLE element   
            - Notes: If there are any notes or additional information that the user should
                be aware of, include them here. This should be a bulleted list. This is an 
                option section and should be omitted if there are no notes. 

        Never include any markdown langauage hints (e.g., ```, ```markdown, etc.) or any 
        other text in the output. The first line should be the title. The very first character 
        should be the # symbol.
    """

    messages: List[SystemMessage | UserMessage] = [
        SystemMessage(content=system_prompt),
        UserMessage(
            content=f"Here is the research document:\n{research_document}\n",
            source="user",
        ),
        UserMessage(
            content=f"Here is the user's hunting hypothesis: {hypothesis}\n",
            source="user",
        ),
        UserMessage(
            content=f"Here is the local data document:\n{local_data_document}\n",
            source="user",
        ),
        UserMessage(
            content=f"Additional local context: {local_context}\n", source="user"
        ),
    ]

    # If we have messages from a previous run, add them so we can continue the research
    if previous_run:
        messages = messages + previous_run

    able_table_client = await get_model_client(agent_name="able_table")

    # Call the LLM using the configured provider client
    try:
        result = await able_table_client.create(messages)  # Await the async method
        # Access the content from the CreateResult object
        return str(
            result.content
        )  # Use the correct attribute to access the generated content
    except Exception as e:
        return f"Error while generating hypotheses: {e}"
