# Copyright (c) 2025 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# SPDX-License-Identifier: MIT

from typing import Optional

from autogen_agentchat.messages import TextMessage
from autogen_agentchat.agents import AssistantAgent
from autogen_agentchat.teams import RoundRobinGroupChat
from autogen_agentchat.ui import Console
from autogen_agentchat.conditions import TextMentionTermination
from autogen_agentchat.base import TaskResult

from ..utils.llm_factory import get_model_client
from ..utils.plan_grounding import check_plan_grounding
from ..utils.result_extractors import extract_hunt_plan


async def plan_hunt(
    research_document: str,
    local_data_document: str,
    hypothesis: str,
    able_info: str,
    data_discovery: str,
    local_context: str,
    verbose: bool = False,
    previous_run: Optional[list] = None,
    msg_preprocess_callback=None,
    msg_preprocess_kwargs=None,
    msg_postprocess_callback=None,
    msg_postprocess_kwargs=None,
) -> TaskResult:
    """
    Agent that consumes data produced by all the other PEAK Prepare-phase agents and
    produces a comprehensive plan for the hunt.

    Args:
        research_document (str): The research document containing threat hunting techniques.
        local_data_document (str): The local data document containing information about the data sources available in the Splunk server.
        hypothesis (str): The hunting hypothesis to be tested.
        able_info (str): The Actor, Behavior, Location and Evidence (ABLE) information.
        data_discovery (str): The data discovery information.
        local_context (str): Additional local context to consider.
        verbose (bool): Whether to enable verbose output.

    Returns:
        str: The output generated by the LLM.
    """
    # Define the system prompt for the planner agent
    planner_prompt = """
        You are an expert in cybersecurity threat hunting. As the agent in charge of planning
        the hunt, your task is to create a comprehensive plan based on the provided hypothesis,
        technique/behavior research document, Actor, Behavior, Location and Evidence (ABLE) 
        information, information about the relevant data source(s) available in the Splunk server,
        and any additional local context provided. This local context may include key information 
        about the computing environment, network or Internet infrastructure, pointers for
        getting the most out of the Splunk server, or other relevant information that may be of
        use to you in your planning.

        Read the research document carefully, as well as the hypothesis that goes with it.
        Correlate these with the ABLE information, paying special attention to:
        - The Actor: Who is the threat actor, if known? Not every hunt will have a 
          specific actor, but if one is known, it may help you focus your hunt.
        - The Behavior: What is the behavior or technique that the threat actor is using?
        - The Location: Where is the threat actor operating? This may be a specific
          geographic location, a specific network, a part of the network (e.g., "the DMZ"
          or "the finance users"), or even a specific system.
        - The Evidence: What evidence is available to support the hypothesis? This may include
          specific data sources, logs, or other information that can be used to test the hypothesis.
          The data discovery information will be helpful here. The Evidence data may also include
          how the behavior is expected to manifest in the data sources, such as specific
          fields or values that are expected to be present in the data.

        Use the data discovery information to identify the relevant Splunk indices or data sources
        that contain the data needed to test the hypothesis. The data discovery information
        will provide you with a list of potential Splunk indices, their descriptions, 
        relevant sourcetypes and the key fields that are most likely to contain the 
        data needed to test the hypothesis.

        GROUNDING RULES for Splunk indices and SPL syntax (mandatory):
        - ONLY use index names that appear in the data discovery information. Every index
          you name must be traceable to that document. If the discovery information reports
          an index as absent, or does not mention an index, do not use it in any query —
          even if it sounds plausible or standard (e.g., "netflow", "audit", "endpoint").
        - Never invent index, sourcetype, or field names. Field names must also come from
          the data discovery information's key-fields lists.
        - If the discovery information is missing an index your hunt seems to need, do not
          silently substitute a different one: instead state the gap explicitly in the
          plan's Data section ("required data not present in the discovered indices").
        - SPL syntax constraints: the 'tstats' command does not support FROM_UNIXTIME, and
          tstats aggregations over _time are limited to count/min/max/range/earliest/latest.
          Every query you write must be executable SPL as-is: no placeholder values like
          "earliest" or "latest" in place of real time-range arguments, no pseudocode,
          and no "[rest of the query]" style elisions. Use "earliest=-24h latest=now" style
          arguments when a time range is needed.

        Using all this information, create a comprehensive plan for the hunt that includes:
        - A restatement of the hypothesis. Call this section "Hypothesis".
        - An estimate of the applicable time window for the hunt. Many hunts may not have 
          a specific recommendation for a time window, but certain hunts looking for 
          time-based patterns (e.g., establishing a baseline for normal activity) will benefit
          or even require a longer time window. Examples would be "Previous 30 days", "7 days",
          or "Year-to-date", but these are not the only possible values. If no specific 
          window is recommended, just write "No specific time window recommended". Call this 
          section "Recommended Time Frame".
        - A concise restatement of the ABLE information in table form. Remember to take into account
          the results of the data discovery when specifying the Evidence. 
          Call this section "ABLE Table".
        - A concise list of the relevant Splunk indices, sourcetypes, key fields, and their
          relevance to the hunt, in table form. Call this section "Data".
        - A detailed plan for the hunt, including the steps to be taken, the data sources 
          to be used, specific Splunk SPL queries to be run, and guidance on how to 
          interpret their results. Number the steps in the order in which they must be performed.
          Include any other analysis or investigation steps necessary to
          find the type of activity described in the hypothesis. You do not need to perform a 
          full incident response investigation, but you should provide enough detail to allow
          the hunter to identify the activity and determine whether it is likely to be malicious.
          Call this section "Hunt Procedure".
        
        Keep the following in mind when planning:
        - Because the Splunk indices may contain a very large amount of data, be as 
          specific as possible when specifying the data sources to be used. For example,
          when feasible, specify the index and sourcetype with all queries. Also use 
          search filters to limit the amount of data being searched, such as by specifying
          certain specific fields and values that must be present to make the events
          relevant. 
        - Instead of using traditional queries, consider using the SPL 'tstats' command
          to search indexed data, as this is more efficient and faster than searching raw logs.
        - Respect the GROUNDING RULES above in every query: they take precedence over
          efficiency suggestions, and an executable query against a discovered index is
          worth more than an efficient query against an index that does not exist.

        Respond with a Markdown document containing the detailed hunt plan.  Only return
        your plan in the response, do not include any other text. Do not offer
        to provide more information or suggest additional tasks. Do not include information
        about revisions you made in response to feedback from the critic agent. The only 
        output should be the Markdown document containing the hunt plan.

        Anyone who reads this plan will already know it will be in Markdown format,
        so you never begin it with "```markdown", "```" or similar. Just start with
        the first section of the plan.
        
        When receiving feedback from a critic agent, incorporate their advice into your
        existing plan in order to provide the best quality plan.

        In the event that you are unable to create a comprehensive plan, respond with
        "Could not create a hunt plan" and provide a bullet list of the reasons why you
        could not create a plan. This will help the critic agent understand
        the limitations of your plan and provide constructive feedback.
    """

    plan_critic_prompt = """
        You are an expert in cybersecurity threat hunting. As the hunt plan critic agent,
        your task is to review the hunt plans generated by the hunt planner agent
        and provide constructive feedback to improve the quality of the plans. 

        Carefully review the provided hunting hypothesis to ensure that the plan's 
        restatement of the hypothesis is accurate to the user's original intent, then
        review the entire research document and plan to ensure that the plan is
        comprehensive, actionable, and detailed enough to allow a hunter to execute
        the hunt effectively.

        Ensure that the plan includes:
        - A restatement of the hypothesis.
        - An estimate of the applicable time window for the hunt.
        - A concise restatement of the ABLE information in table form.
        - A concise list of the relevant Splunk indices, sourcetypes, key fields, and their
          relevance to the hunt, in table form.
        - A detailed plan for the hunt, including the steps to be taken, the data sources
          to be used, specific Splunk SPL queries to be run, and guidance on how to
          interpret their results. 
        - Any other analysis or investigation steps necessary to find the type of activity
          described in the hypothesis. Especially ensure that any local context provided
          is taken into account in the plan, and that the plan is tailored to the specific
          environment and data sources available.

        Above all else, ensure that the plan and the analysis steps actually address
        the hunting hypothesis. 

        Be sure to carefully check every Splunk SPL query provided in the plan. The planner
        must obey the GROUNDING RULES from its instructions; treat any violation as a blocking
        defect and require a fix, no matter how good the rest of the plan is:
        - An index, sourcetype, or field name that does not appear in the data discovery
          information is a fabrication (observed live: "netflow", "audit", "endpoint" cited
          for a deployment where discovery reported them absent). Require removal or
          replacement with a discovered index, or an explicit data-gap statement.
        - A query that is not executable as-is is a fabrication too: placeholder time ranges
          ("WHERE _time > earliest"), pseudocode, "[rest of the query]" elisions, or invalid
          syntax such as FROM_UNIXTIME inside tstats. Require a rewritten, executable query.
        Keep
        in mind that the Splunk indices may contain a very large amount of data, so
        the queries should be as efficient as possible — but only after the queries are
        grounded and executable. If the queries are not efficient or do not use
        the correct indices, sourcetypes, or key fields, provide specific feedback on how to
        improve them.

        If there are any issues with the plan, if any steps are missing or unclear, 
        or if the plan does not provide enough detail to allow the hunter to execute 
        the hunt effectively or to easily interpret the query outputs, provide 
        constructive feedback to the planner agent to allow it to improve the plan. 
        Be specific about what needs to be changed and why. Be picky about the details, 
        as the hunter will rely on your feedback to improve the plan.

        If the plan is comprehensive and actionable, respond with "YYY-TERMINATE-YYY" 
        to indicate that the planner agent can stop iterating.
    """

    messages = [
        TextMessage(
            content=f"Here is the research document:\n{research_document}\n",
            source="user",
        ),
        TextMessage(
            content=f"Here is the local data document:\n{local_data_document}\n",
            source="user",
        ),
        TextMessage(content=f"Here is the hypothesis: {hypothesis}\n", source="user"),
        TextMessage(
            content=f"The Actor, Behavior, Location and Evidence (ABLE) information is as follows: {able_info}",
            source="user",
        ),
        TextMessage(
            content=f"Data discovery information: {data_discovery}\n", source="user"
        ),
        TextMessage(
            content=f"Additional local context: {local_context}\n", source="user"
        ),
    ]

    # If we have messages from a previous run, add them so we can continue the planning
    if previous_run:
        messages = messages + previous_run

    hunt_planner_client = await get_model_client(agent_name="hunt_planner")
    hunt_plan_critic_client = await get_model_client(agent_name="hunt_plan_critic")

    planning_agent = AssistantAgent(
        "hunt_planner",
        model_client=hunt_planner_client,
        system_message=planner_prompt,
    )

    plan_critic_agent = AssistantAgent(
        "hunt_plan_critic",
        model_client=hunt_plan_critic_client,
        system_message=plan_critic_prompt,
    )

    # Define a termination condition that stops the task once the critic
    # agent has approved the hunt plan.
    text_termination = TextMentionTermination("YYY-TERMINATE-YYY")

    team = RoundRobinGroupChat(
        participants=[planning_agent, plan_critic_agent],
        termination_condition=text_termination,
    )

    # Preprocess the messages
    if msg_preprocess_callback:
        messages = msg_preprocess_callback(
            msgs=messages, **(msg_preprocess_kwargs or {})
        )

    # Grounding revision round (fork fix, finding 10): run the deterministic
    # checks on the first plan; if it cites undiscovered indices or non-
    # executable SPL, feed the specific violations back as a user message and
    # run the team once more. The RoundRobin team starts at the planner, so
    # the planner sees the violations and revises before the critic speaks.
    # One round only: the checks are advisory at 7B (the planner may still
    # violate), and the CLI-level GROUNDING warning remains the final gate.
    try:
        if verbose:
            result = await Console(team.run_stream(task=messages), output_stats=True)
        else:
            result = await team.run(task=messages)

        # Deterministic grounding check on the first plan.
        first_plan = extract_hunt_plan(result)
        report = check_plan_grounding(first_plan, data_discovery or "")
        if not report.ok:
            violations = []
            if report.undiscovered_indices:
                violations.append(
                    "Indices cited but not in the data discovery report: "
                    + ", ".join(report.undiscovered_indices)
                )
            for query in report.suspicious_queries:
                violations.append(f"Not executable as written: {query}")
            revision_feedback = (
                "GROUNDING REVISION REQUIRED. Your plan violates the grounding rules: "
                + " | ".join(violations)
                + " Revise the plan: use only indices from the data discovery "
                "information, and make every query executable SPL as-is. If required "
                "data is genuinely absent, replace the affected query with an explicit "
                "data-gap statement in the plan's Data section."
            )
            if verbose:
                print(
                    "Grounding violations detected — requesting one revision round:\n"
                    "  " + "\n  ".join(violations)
                )
            revision_messages = messages + [
                TextMessage(content=revision_feedback, source="user")
            ]
            if verbose:
                result = await Console(
                    team.run_stream(task=revision_messages), output_stats=True
                )
            else:
                result = await team.run(task=revision_messages)

        # Postprocess the result
        if msg_postprocess_callback:
            result = msg_postprocess_callback(
                result=result, **(msg_postprocess_kwargs or {})
            )

        return result
    except Exception as e:
        print(f"Error during hunt planning: {e}")
        raise Exception("An error occurred while planning the hunt.") from e
